[project]
name = "k8s_dashboard"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "ansi2html>=1.9.2",
    "flask>=3.1.2",
    "flask-sock>=0.7.0",
    "gunicorn>=23.0.0",
    "kubernetes>=33.1.0",
]
