[project]
name = "dashboard"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "flask>=3.1.2",
    "gunicorn>=23.0.0",
    "kubernetes>=33.1.0",
]
